name: Deploy on Hydrolia Server

on: 
  workflow_dispatch: # Activation manuelle possible
  push:
    branches:
      - prod  # Déclenche seulement sur prod

jobs:
  check_quality_gate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}  # Ne s'exécute pas si c'est un workflow manuel
    steps:
      - name: Check Quality Gate
        id: sonar
        run: |
          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=LateFR_Hydrolia" \
            | jq -r '.projectStatus.status')

          echo "Quality Gate status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "Quality Gate failed, stopping workflow."
            exit 1
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          # Si c'est un déclenchement manuel, on affiche un message et on passe directement au déploiement
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Bypassing quality gate check due to manual trigger."
          else
            echo "Running quality gate check..."
          fi
          
          # Effectue le déploiement
          response=$(curl -s -w "%{http_code}" -X POST "http://88.160.36.153:50080/redeploy/front-end?secret_key=${{ secrets.DEPLOY_TOKEN }}" -o response.json)
          
          # Vérifie le code de statut HTTP
          if [[ "$response" -ne 200 ]]; then
            echo "Deployment failed with status code $response."
            cat response.json
            exit 1
          fi
          
          echo "Deployment succeeded."
